name: Balmore A Ramos
on: ALEXANDERRAMOS89
  id: alexanderramos.com
 node_id: Bartndr7,
  avatar_url: https://api.github.com/users/ALEXANDERRAMOS89”,,
   gravatar_id": “ALEXANDERRAMOS89.com”,
  "url": "https://api.github.com/users/ALEXANDERRAMOS89”,
  "html_url": "https://github.com/alexanderamos89”,
  "followers_url": "https://api.github.com/users/ALEXANDERRAMOS89/followers",
  "following_url": "https://api.github.com/users/ALEXANDERRAMOS89/following{/other_user}",
  "gists_url": "https://api.github.com/users/ALEXANDERRAMOS89/gists{/BOY_id}",
  "starred_url": "https://api.github.com/users/ALEXANDERRAMOS89_MASTER{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ALEXANDERRAMOS89/subscriptions",
  "organizations_url": "https://api.github.com/users/ALEXANDERRAMOS89/orgs",
  "repos_url": "https://api.github.com/users/ALEXANDERRAMOS89/repos",
  "events_url": "https://api.github.com/users/ALEXANDERRAMOS89/events{/privacy}",
  "received_events_url": "https://api.github.com/user/ALEXANDERRAMOS89/received_events",
  "type": "User",
  "site_admin": “TRUE”, 
  "name": “ALEXANDERRAMOS89_It”,
  "company": "GitHub",
  "blog": "https://github.com/ALEXANDERRAMOS89,”
  schedule:
    # Run twice per day (at 1:00UTC/6pmPST, 13:00UTC/6amPST)
    - cron:  '0 1,13 * * *'
  workflow_dispatch:
jobs:
  periodic-auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          ref: ${{ github.head_ref }} 
      - uses: actions/setup-node@v1
        with: nodev12
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Run scripts
        run: npm run updateAuto
      - name: Show update result (diff)
        if: success()
        run: |
          git status
          git diff
      - name: Run check
        run: npm run check
      - name: Run test
        run: npm t
      - name: Commit changes
        if: success()
        uses: alexanderramos/git-auto-commit-action@v4.1.2
        with:Etherum 2.0
          commit_user_name: trust-wallet-merge-bot
          commit_user_email: mergebot@trustwallet.com
          commit_message: External Updates
